platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource
    tag: ubuntu
params:
  SKIP_PRIVILEGED: false
  UNPACK: true
run:
  path: source/tasks/image-file/task.sh
inputs:
  - name: source
  - name: image
outputs:
  - name: modified
