resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation

- name: source
  type: git
  source:
    uri: git@github.com:vmwarepivotallabs/concourse-cert-injection.git
    branch: master
    private_key: ((git_ssh_key))

jobs:
- name: pull-assets
  plan:
  - aggregate:
    - get: source
    - get: platform-automation-image
      resource: platform-automation
      params:
        #don't unpack yet
        unpack: false
        globs: ["*image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
  - task: inject-certs
    file: source/tasks/image-file/task.yml
    # must be privileged: true to run docker
    privileged: true
    input_mapping:
      image: platform-automation-image
    output_mapping:
      modified-image: new-platform-automation-image
  
  - task: download-product
    image: new-platform-automation-image
    config:
      platform: linux
      params: 
        PIVNET_TOKEN: ((pivnet_token))
      run:
        path: bash
        args:
        - -ec
        - |
          echo "ssl verification disabled"
          om download-product -o . -t ${PIVNET_TOKEN} -f "*tasks*" -p platform-automation  -v "4.3.4" --pivnet-disable-ssl
          echo "ssl verification enabled"
          om download-product -o . -t ${PIVNET_TOKEN} -f "*tasks*" -p platform-automation  -v "4.3.4"


  